services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_dev_assistant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/ai_dev_assistant
    env_file: .env
    depends_on:
      - db

volumes:
  db_data:
