services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_dev_assistant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/ai_dev_assistant
    env_file: .env
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      # This is not ideal, dont have enough time to debug this fully at the moment but works for a proof of concept
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "8080:3000"
    environment:
      VITE_API_URL: "http://localhost:8000"
    depends_on:
      - backend

volumes:
  db_data:
